

BEGIN;

-- -------------------------------------------------------------
-- 1. ROLES
-- Se crea primero porque EMPLEADOS depende de esta tabla.
-- -------------------------------------------------------------
CREATE TABLE roles (
    id_rol      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL,

    CONSTRAINT pk_roles
        PRIMARY KEY (id_rol),
    CONSTRAINT uq_roles_descripcion
        UNIQUE (descripcion)
);

-- -------------------------------------------------------------
-- 2. CLIENTES
-- Los campos activo implementan borrado logico (soft delete).
-- -------------------------------------------------------------
CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(100) NOT NULL,
    apellido   VARCHAR(100) NOT NULL,
    dni        VARCHAR(15) NOT NULL,
    email      VARCHAR(254) NOT NULL,
    telefono_1 VARCHAR(30) NOT NULL,
    telefono_2 VARCHAR(30),
    direccion  VARCHAR(255),
    activo     BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_clientes
        PRIMARY KEY (id_cliente),
    CONSTRAINT uq_clientes_dni
        UNIQUE (dni),
    CONSTRAINT uq_clientes_email
        UNIQUE (email)
);

-- -------------------------------------------------------------
-- 3. EMPLEADOS
-- Todo empleado debe tener un rol asignado.
-- -------------------------------------------------------------
CREATE TABLE empleados (
    id_empleado  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_rol       INTEGER NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    apellido     VARCHAR(100) NOT NULL,
    dni          VARCHAR(15) NOT NULL,
    departamento VARCHAR(100) NOT NULL,
    activo       BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_empleados
        PRIMARY KEY (id_empleado),
    CONSTRAINT uq_empleados_dni
        UNIQUE (dni),
    CONSTRAINT fk_empleados_roles
        FOREIGN KEY (id_rol)
        REFERENCES roles (id_rol)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- -------------------------------------------------------------
-- 4. TICKETS
-- Guarda el cliente y el empleado asignado actualmente.
-- -------------------------------------------------------------
CREATE TABLE tickets (
    id_ticket    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente   INTEGER NOT NULL,
    id_empleado  INTEGER NOT NULL,
    canal_origen VARCHAR(20) NOT NULL,
    activo       BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_tickets
        PRIMARY KEY (id_ticket),
    CONSTRAINT fk_tickets_clientes
        FOREIGN KEY (id_cliente)
        REFERENCES clientes (id_cliente)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_tickets_empleados
        FOREIGN KEY (id_empleado)
        REFERENCES empleados (id_empleado)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT ck_tickets_canal_origen
        CHECK (canal_origen IN (
            'chat',
            'email',
            'whatsapp',
            'telefono',
            'web'
        ))
);

-- -------------------------------------------------------------
-- 5. TICKET_LOGS
-- Conserva el historial de estados y el empleado responsable.
-- -------------------------------------------------------------
CREATE TABLE ticket_logs (
    id_ticket_log INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_ticket     INTEGER NOT NULL,
    id_empleado   INTEGER NOT NULL,
    fecha         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado        VARCHAR(20) NOT NULL,

    CONSTRAINT pk_ticket_logs
        PRIMARY KEY (id_ticket_log),
    CONSTRAINT fk_ticket_logs_tickets
        FOREIGN KEY (id_ticket)
        REFERENCES tickets (id_ticket)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT fk_ticket_logs_empleados
        FOREIGN KEY (id_empleado)
        REFERENCES empleados (id_empleado)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT ck_ticket_logs_estado
        CHECK (estado IN (
            'abierto',
            'en_proceso',
            'resuelto',
            'cerrado',
            'reabierto'
        ))
);

-- -------------------------------------------------------------
-- 6. CONVERSACIONES
-- La calificacion es opcional y se completa al finalizar.
-- -------------------------------------------------------------
CREATE TABLE conversaciones (
    id_conversacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_ticket       INTEGER NOT NULL,
    calificacion    SMALLINT,
    fecha           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_conversaciones
        PRIMARY KEY (id_conversacion),
    CONSTRAINT fk_conversaciones_tickets
        FOREIGN KEY (id_ticket)
        REFERENCES tickets (id_ticket)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT ck_conversaciones_calificacion
        CHECK (calificacion BETWEEN 1 AND 5)
);

-- -------------------------------------------------------------
-- 7. CONSULTAS
-- Cada consulta pertenece a una conversacion.
-- -------------------------------------------------------------
CREATE TABLE consultas (
    id_consulta     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_conversacion INTEGER NOT NULL,
    pregunta        TEXT NOT NULL,

    CONSTRAINT pk_consultas
        PRIMARY KEY (id_consulta),
    CONSTRAINT fk_consultas_conversaciones
        FOREIGN KEY (id_conversacion)
        REFERENCES conversaciones (id_conversacion)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT ck_consultas_pregunta_no_vacia
        CHECK (LENGTH(pregunta) > 0)
);

-- -------------------------------------------------------------
-- 8. RESPUESTAS
-- es_humano = FALSE: respuesta generada por IA.
-- es_humano = TRUE: respuesta generada o corregida por una persona.
-- -------------------------------------------------------------
CREATE TABLE respuestas (
    id_respuesta       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_consulta        INTEGER NOT NULL,
    texto_respuesta    TEXT NOT NULL,
    es_humano          BOOLEAN NOT NULL DEFAULT FALSE,
    es_respuesta_final BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_respuestas
        PRIMARY KEY (id_respuesta),
    CONSTRAINT fk_respuestas_consultas
        FOREIGN KEY (id_consulta)
        REFERENCES consultas (id_consulta)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT ck_respuestas_texto_no_vacio
        CHECK (LENGTH(texto_respuesta) > 0)
);

COMMIT;

